### PR TITLE
De deprecation

### PR DESCRIPTION
**Pull request by gangstead**
I removed half the deprecation warnings.  The remaining `workspaceView` calls will need a little more work.

### CODE REVIEW

**Comment by gangstead** [comment]
Atom made all `workspaceView` calls deprecated at some point.  It throws up an annoying warning triangle at the bottom for all users of packages with those calls.  This update fixes half of the warnings.   You'll have to do an `apm publish patch` to get them out in the wild.

**Comment by mkleehammer** [comment]
Thanks for the work.  I'm looking for a new maintainer for this package since I am now back to using emacs.  Are you interested?

**Comment by mkleehammer** [comment]
Published.  (Unfortunatley I published as a minor.  I should not hurry these things.)

**Comment by gangstead** [comment]
Yeah sure.  I don't promise much, but I can probably keep the deprecation warnings at bay.

**Comment by mkleehammer** [comment]
@gangstead Can I transfer this repo to you now that I'm not working on Atom anymore?  You would simply need to update the package.json file to point to your repo.

**Comment by gangstead** [comment]
Sure.  You can transfer to me or make me a collaborator on your repo.

**Comment by mkleehammer** [comment]
Thanks. On its way.

**Comment by mkleehammer** [comment]
Actually, not working - there is already a gangstead/atom-incremental-search.  Can you rename or delete yours for the transfer?

**Comment by gangstead** [comment]
Done.

**Comment by mkleehammer** [comment]
Holy smokes - now it says: "gangstead already has a repository in the mkleehammer/atom-incremental-search network"

I guess you have to delete it from GitHub?  (Don't forget to keep a copy on disk though.)  This is surprising - GitHub usually DWIM.

**Comment by gangstead** [comment]
Gone. There's no going back now.

**Pull request merged**
